# netlify.toml
[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.57.2"
  HUGO_EXTENDED = "true"
  HUGO_ENV = "production"
  # (optionally keep or remove)
  HUGO_ENABLEGITINFO = "true"
