[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  # Pin a modern extended Hugo version (works with Academic/Wowchemy)
  HUGO_VERSION = "0.111.3"
  HUGO_EXTENDED = "true"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
